export interface receiveContractFileDataModels {
       id: number,
       receiveContractId: number,
       title: string,
       documentImg: string,
       documentDescription: string,
       receiveContract: string,
}

export interface ReceiveContractModel {
       id: number,
       receiverId: number,
       receiverName: string,
       receiverPhoneNumber: string,
       contractGroupId: number,
       customerName: string,
       customerPhoneNumber: string,
       customerAddress: string,
       customerCitizenIdentificationInfoNumber: string,
       customerCitizenIdentificationInfoAddress: string,
       customerCitizenIdentificationInfoDateReceive: Date | null,
       modelName: string,
       carLicensePlates: string,
       seatNumber: number,
       dateReceive: Date | null,
       receiveAddress: string,
       currentCarStateSpeedometerNumber: number,
       currentCarStateFuelPercent: number,
       currentCarStateCurrentEtcAmount: number,
       currentCarStateCarStatusDescription: string,
       currentCarStateCarFrontImg: string,
       currentCarStateCarBackImg: string,
       currentCarStateCarLeftImg: string,
       currentCarStateCarRightImg: string,
       currentCarStateCarInteriorImg: string,
       currentCarStateCarBackSeatImg: string,
       currentCarStateCarPhysicalDamage: string,
       insuranceMoney: number,
       depositItemPaper: string,
       depositItemAsset: string,
       depositItemAssetInfo: string,
       isExported: boolean,
       customerSignature: string,
       staffSignature: string,
       filePath: string,
       fileWithSignsPath: string,
       contractStatusId: number,
       originalCondition: boolean,
       currentCarStateCarDamageDescription: string,
       ortherViolation: string,
       detectedViolations: boolean,
       speedingViolationDescription: string,
       forbiddenRoadViolationDescription: string,
       trafficLightViolationDescription: string,
       extraTime: number,
       unpaidTicketMoney: number,
       transferContractId: number,
       depositItemDescription: string,
       receiveContractFileDataModels: receiveContractFileDataModels[],
       violationMoney: number,

}
